/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package idv.patrick.media;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int icon_add=0x7f020001;
        public static final int icon_bookmark=0x7f020002;
        public static final int icon_delete=0x7f020003;
        public static final int icon_notifications=0x7f020004;
        public static final int icon_play=0x7f020005;
        public static final int icon_preferences=0x7f020006;
        public static final int icon_recent=0x7f020007;
        public static final int icon_start=0x7f020008;
        public static final int icon_stop=0x7f020009;
        public static final int icon_sync=0x7f02000a;
        public static final int icon_video=0x7f02000b;
        public static final int icon_view_details=0x7f02000c;
        public static final int video=0x7f02000d;
    }
    public static final class id {
        public static final int empty=0x7f070000;
        public static final int menu_item_preferences=0x7f070004;
        public static final int progress_indicator=0x7f070003;
        public static final int surface=0x7f070002;
        public static final int title=0x7f070001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int media_scanner_activity=0x7f030001;
        public static final int player=0x7f030002;
    }
    public static final class menu {
        public static final int media_list_option=0x7f060000;
    }
    public static final class string {
        public static final int about_message=0x7f05000d;
        public static final int about_title=0x7f05000c;
        public static final int activity_media_list=0x7f050004;
        public static final int activity_player_panel=0x7f050005;
        public static final int activity_settings=0x7f050006;
        public static final int app_name=0x7f050000;
        public static final int media_on_error=0x7f05000b;
        public static final int menu_item_preferences=0x7f050007;
        public static final int msg_loading_video=0x7f05000a;
        public static final int no_videos=0x7f05000e;
        public static final int preferences_auto_rotate=0x7f050001;
        public static final int preferences_auto_rotate_summary=0x7f050002;
        public static final int preferences_player_category=0x7f050003;
        public static final int preferences_show_debug_info=0x7f050008;
        public static final int preferences_show_debug_info_summary=0x7f050009;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
